### ISSUE TITLE
X-Lite.download.recipe failing (product looks to be discontinued)

### ISSUE THREAD

**Issue by neilmartin83** [autopkg/ygini-recipes#23]
Heya,

It looks like X-Lite has become "Bria Free" - https://www.counterpath.com/x-lite-download/

The download URL this recipe grabs is now failing with Access Denied errors - e.g.: https://counterpath.s3.amazonaws.com/downloads/X-Lite_5.8.3_102652.dmg 

I had a look but couldn't find any direct download links/scrapeable pages for Bria :-(

**Comment by macmule** [comment]
Bria Free is now Bria.. or Bria solo or Bria Teams.. anyways we have recipes for them at: https://github.com/autopkg/dataJAR-recipes/tree/master/Bria
