### ISSUE TITLE
TripMode.download.recipe - Issue with SparkleUpdateInfoProvider

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/ygini-recipes#25]
```
SparkleUpdateInfoProvider
{'Input': {'appcast_url': 'https://www.tripmode.ch/app/appcast.xml'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 676, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 483, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/SparkleUpdateInfoProvider.py", line 301, in main
    items = self.parse_feed_data(data)
  File "/Library/AutoPkg/autopkglib/SparkleUpdateInfoProvider.py", line 216, in parse_feed_data
    raise ProcessorError("No channel items were found in appcast feed.")
autopkglib.ProcessorError: No channel items were found in appcast feed.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 676, in process
    self.env = processor.process()
No channel items were found in appcast feed.
Failed.
Receipt written to /Users/sadmin/Library/AutoPkg/Cache/local.munki.TripMode-dataJAR/receipts/local.munki-receipt-20201016-135211.plist

The following recipes failed:
    local.munki.TripMode-dataJAR
        Error in local.munki.TripMode-dataJAR: Processor: SparkleUpdateInfoProvider: Error: No channel items were found in appcast feed.
```

It looks like the Sparklefeed URL (https://www.tripmode.ch/app/appcast.xml) now 404's. I can knock up a PR to switch to scraping the site (https://tripmode.ch/tripmode2/) if you're happy with that change?

There's also now a version 3 but this is only supported on Big Sur (https://tripmode.ch).

Let me know if you have a preference for the current recipe and I'll see about getting a PR in 😊

**Comment by neilmartin83** [comment]
Should be fixed in PR #26 - the Sparkle URL has changed but still lists v2.2.1 as the latest.

**Comment by Daz-wallace** [comment]
Re-opening as it looks like the URL from the new Sparkle feed 404's - https://www.tripmode.ch/app/TripMode-2.2.1-782-app.dmg

The website download page (https://tripmode.ch/thank-you-for-downloading-tripmode/) serves 2.3.0.

I think it's worth switching away from the Sparkle URL?

**Comment by Daz-wallace** [comment]
Oh I can't reopen. I'll log a new issue
