### ISSUE TITLE
Re-opening as it looks like the URL from the new Sparkle feed 404's

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/ygini-recipes#27]
Re-opening as it looks like the URL from the new Sparkle feed 404's - https://www.tripmode.ch/app/TripMode-2.2.1-782-app.dmg

The website download page (https://tripmode.ch/thank-you-for-downloading-tripmode/) serves 2.3.0.

I think it's worth switching away from the Sparkle URL?

_Originally posted by @Daz-wallace in https://github.com/autopkg/ygini-recipes/issues/25#issuecomment-717986685_

**Comment by ygini** [comment]
Hi

Question before validating the change, why having the version 2 in static for the download pattern?

Can't we just look for  `TripMode-*app\.dmg` ?

Otherwise I'm OK with the change

**Comment by Daz-wallace** [comment]
Hey @ygini 

The main reason is that version 3 is for Big Sur only, so I think it would make sense to split out the two. One for v2 and one for v3?

`WARNING: TripMode 3 works only for the upcoming macOS Big Sur. If you run on Catalina or earlier, please download TripMode 2` 
Source: https://tripmode.ch/thank-you-for-downloading-tripmode3/

**Comment by ygini** [comment]
Indeed, one for v2 and one for v3 seems to be a reasonable move.

**Comment by ygini** [comment]
Yes please. Sorry I forgot to answer you!

**Comment by Daz-wallace** [comment]
No worries at all. All done.

Feel free to change as you wish 😊

**Comment by ygini** [comment]
Change integrated! Thanks a lot for your work!
