### ISSUE TITLE
Missing com.github.peshay.download.GlobalProtect

### ISSUE THREAD

**Issue by alavaliant** [autopkg/ygini-recipes#50]
PaloAlto/GlobalProtectMac.munki.recipe sets 
```
        <key>ParentRecipe</key>
        <string>com.github.peshay.download.GlobalProtect</string>
```
But I can't see any sign of a download.GlobalProtect recipe in the repo.    And if I try to use the GlobalProtectMac.munki.recipe without I get an error about that recipe not being found.

Since most other recipes have both a .munki.recipe and a .download.recipe file in their sub directories.   I'm wondering if perhaps the GlobalProtect download.recipe was accidentally not committed and pushed up to the repo?

**Comment by ygini** [comment]
Hello

This is a reference to a download receipt published by Peshay, you need to add his repo to your list of trusted one to have mine working. That's how autopkg works.

**Comment by alavaliant** [comment]
Whoops sorry I completely missed that the download.recipe was in another namespace.
