### ISSUE TITLE
invalid package name for Postico

### ISSUE THREAD

**Issue by krispayne** [autopkg/ygini-recipes#6]
When running this recipe via AutoPkgr, this error occurs:
![screen shot 2016-11-18 at 10 48 24 am](https://cloud.githubusercontent.com/assets/70580/20442196/9a330426-ad7c-11e6-9ffc-2db59a9d49ef.png)

This error did not occur when testing the Recipe Robot generated recipes locally via commandline autopkg, so I'm assuming this may have something to do with the parent recipes, but not sure.

**Comment by ygini** [comment]
Error is in line 44 of your pkg recipe. As said in the error, the version variable does not exist.

You might want to use things like https://github.com/autopkg/autopkg/wiki/Processor-AppDmgVersioner to extract version of the app.

**Comment by krispayne** [comment]
Thanks @ygini let me take a look and see if that resolves it. There are some other downstream error's too, so maybe this is the root.

**Comment by ygini** [comment]
@krispayne did you handled this?

**Comment by krispayne** [comment]
@ygini no, sorry I haven't I will take a look tonight.

**Comment by krispayne** [comment]
@ygini I did work on this, however I am having trouble grokking the debugging of it and was wondering if I could use this as a learning opportunity?

I believe the below snippet that shows what I added for the AppDmgVersioner processor is supposed to work, but I get a hdituil error about the dmg not being recognized, which makes sense in so far as I have only named it with variables and possibly that variable isn't getting expanded.

```
...

<key>Process</key>
	<array>
            <dict>
	        <key>Processor</key>
		<string>AppDmgVersioner</string>
		<key>Arguments</key>
                <dict>
                    <key>dmg_path</key>
                    <string>%RECIPE_CACHE_DIR%/%NAME%</string>
               </dict>
            </dict>
</dict>
		<dict>
			<key>Arguments</key>

...
```

**Comment by ygini** [comment]
Sorry, I didn't looked at the right recipe when I've say AppDmgVersioner. The downloaded content is a app in a zip. I've assumed it was a dmg but it's not.

Since it's a .app, you can directly use https://github.com/autopkg/autopkg/wiki/Processor-AppPkgCreator to create the package.

**Comment by crystalllized** [comment]
Hi guys, I just went to try to use the Postico recipes in this repo and am finding that there still is not any kind of Versioner process in the .pkg recipe here which leads to 'Invalid packge name'. Is this intended to be fixed?

**Comment by ygini** [comment]
Hi @crystalllized 

I'm sorry but my app catalog solution (munki) is robust enough to handle regular app deployment scenario on macOS without requiring package.

I've initially submitted the solution to @krispayne regarding the way to implement the pkg part but with no return.

You could also have contributed to the repo with a PR for this change… I did it since I had time to do it today but it was an easy one and all informations was on the issue to solve it: https://github.com/autopkg/ygini-recipes/blob/e5cffb6812560fcb46f691e0cf33a0cc13a703a3/Postico/Postico.pkg.recipe
